/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accountSol from "./Account.sol";
export type { accountSol };
export type { Counter } from "./Counter";
