---
version: '3'

dotenv:
  - ".env"

tasks:

  clean:
    desc: clean caches and intermediate outputs
    cmds:
      - forge clean
      - npx hardhat clean

  build:
    desc: build the contracts
    cmds:
      - forge build
      - npx hardhat typechain
  test:
    desc: run the tests
    cmds:
      - forge test -vvv
      - npx hardhat test
