name: ci
on:
  push:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup go-task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          echo "${PWD}/bin" >> $GITHUB_PATH

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install node packages
        run: |
          npm install

        id: npm-install

      - name: Build
        run: |
          task build
        id: build

      - name: Tests
        run: |
          task test
        id: test
